import subprocess,json,pathlib,time,shlex
out=pathlib.Path('artifacts/llmwiki-runtime-audit-20260909')
def probe(name,code):
 t=time.perf_counter(); p=subprocess.run(' '.join(shlex.quote(x) for x in ['/Applications/Obsidian.app/Contents/MacOS/Obsidian','vault=Dusk','eval','code='+code.replace(chr(39),chr(34))]),shell=True,capture_output=True,text=True)
 text=p.stdout.strip(); data={'command':['Obsidian','vault=Dusk','eval','code='+code.replace(chr(39),chr(34))],'wall_ms':round((time.perf_counter()-t)*1000,2),'exit_code':p.returncode,'stderr':p.stderr}
 try:data['result']=json.loads(text.removeprefix('=> '))
 except:data['raw']=text
 (out/(name+'.json')).write_text(json.dumps(data,ensure_ascii=False,indent=2));print(name,json.dumps(data.get('result',data),ensure_ascii=False)[:14000])
probe('live-corpus', '''JSON.stringify((()=>{const h=KnowledgeExplorerHub,t=performance.now(),pages=app.vault.getMarkdownFiles().map(f=>({...app.metadataCache.getFileCache(f)?.frontmatter,file:{path:f.path,mtime:f.stat.mtime}})),a=h.dataSource.index(pages).assets,t1=performance.now(),s=LLMWikiWikiReadAdapter.buildSnapshot({assets:a}),t2=performance.now();const qs=[['verified','synthetic-alpha'],['literature','synthetic-alpha'],['literature','원문 전문'],['all','synthetic-alpha'],['pending','synthetic-alpha'],['literature','상상력'],['literature','지식을 넘어 새로운 가능성을 떠올리는 능력'],['literature','회복탄력성'],['literature','상상력 지식 충돌'],['literature','ZXQ_CANARY_UNRELATED_987']];return {timings:{discovery_projection_ms:t1-t,snapshot_ms:t2-t1},pages:pages.length,assets:a.length,snapshot_keys:Object.keys(s),counts:s.counts,rows:s.rows?.map(r=>({path:r.path,type:r.type,trust:r.trust,statement_bytes:r.statement?.length,summary_bytes:r.summary?.length})),queries:qs.map(([mode,query])=>{const q0=performance.now(),r=LLMWikiWikiReadAdapter.browseRead({snapshot:s,mode,query});return {mode,query,ms:performance.now()-q0,ok:r.ok,status:r.status,reason:r.reason,total:r.total,top:r.rows?.[0]&&{path:r.rows[0].path,citations:r.rows[0].citations,title:r.rows[0].title}}})}})())''')
