// Explicit isolated UI verification harness. Not a production entry point.
module.exports = async function(realApp) {
 const fs=require('fs'), path=require('path'), {Modal}=window.obsidian;
 const base=realApp.vault.adapter.basePath, views=path.join(base,'SYSTEM/Views'), out=__dirname;
 const load=n=>require(path.join(views,n+'.js'));
 const review=load('llmwiki-document-canonical-review'), hash=load('llmwiki-hash'), store=load('knowledge-candidate-store'), reader=load('llmwiki-resurfacing-read-adapter');
 const surface=load('llmwiki-wiki-surface'), readService=load('llmwiki-wiki-read-service'), readAdapter=load('llmwiki-wiki-read-adapter');
 window.LLMWikiWikiReadService=readService; window.LLMWikiWikiReadAdapter=readAdapter;
 const expectations=JSON.parse(fs.readFileSync(path.join(out,'../../expectations.json'),'utf8'));
 const recorded=JSON.parse(fs.readFileSync(path.join(out,'../../live-inspection.json'),'utf8'));
 const root=fs.mkdtempSync(path.join(out,'vault-')), files=new Map(), events=[], completions=[], provider=[];
 const resolve=p=>{const full=path.resolve(root,p);if(!full.startsWith(root+path.sep))throw Error('fixture_scope_escape');return full;};
 const register=p=>{const f={path:p,extension:path.extname(p).slice(1),basename:path.basename(p,'.md')};files.set(p,f);return f;};
 const read=f=>fs.readFileSync(resolve(f.path),'utf8');
 const vault={getAbstractFileByPath:p=>files.get(p)||null,getFiles:()=>[...files.values()],getMarkdownFiles:()=>[...files.values()].filter(f=>f.extension==='md'),read:async f=>read(f),cachedRead:async f=>read(f),createFolder:async p=>fs.mkdirSync(resolve(p),{recursive:true}),create:async(p,b)=>{fs.mkdirSync(path.dirname(resolve(p)),{recursive:true});fs.writeFileSync(resolve(p),b,{flag:'wx'});events.push({kind:'create',path:p});return register(p);},modify:async(f,b)=>{fs.writeFileSync(resolve(f.path),b);events.push({kind:'modify',path:f.path});},delete:async()=>{throw Error('fixture_delete_forbidden');}};
 const pluginCache=new Map(); const isolated={vault,metadataCache:{getFileCache:f=>{try{return {frontmatter:store.parseLifecycleDocument(read(f))};}catch{return {frontmatter:{}};}}},plugins:{getPlugin(id){if(pluginCache.has(id))return pluginCache.get(id);const p=realApp.plugins.getPlugin(id);if(!p)return p;const api=Object.fromEntries(Object.entries(p.api).map(([k,v])=>[k,typeof v==='function'?v.bind(p.api):v]));api.requestStructured=async request=>{const start=Date.now();const response=await p.api.requestStructured(request);provider.push({consumer_id:request.consumer_id,prompt:request.prompt,response,latency_ms:Date.now()-start});return response;};const proxy={...p,api};pluginCache.set(id,proxy);return proxy;}}};
 for(const c of expectations.cases)await vault.create(c.virtual_path,c.text);
 const bText='해솔-842 점검 기록에는 장치 식별자를 함께 적는다.',bPath='INBOX/supplement_b.md';await vault.create(bPath,bText);
 function fromRecorded(id,title){const r=recorded.results.find(r=>r.id===id).result;return {review_id:'mac_ui_'+id,title,document_body:'# '+title+'\n\n'+r.answers.map(a=>a.text+' [원문]('+a.citation.source_path.split('/').map(encodeURIComponent).join('/')+'#'+a.citation.locator.split('#')[1]+')').join('\n\n')+'\n'+(r.review_notes||[]).map(n=>'\n> '+n).join(''),grounded_claims:r.answers.map(a=>({text:a.text,citations:[{...a.citation,evidence_quote:a.citation.excerpt}]}))};}
 const A=fromRecorded('conditions','해솔-842 점검'); A.document_body+='\n\n## 사용자 메모\n시험용 모형에만 적용한다는 개인 검토 메모를 보존한다.\n';
 const B={review_id:'mac_ui_b',title:'점검 기록 보완',document_body:'## 점검 기록 보완\n'+bText+'\n',grounded_claims:[{text:bText,citations:[{source_id:'source_supplement_b',source_path:bPath,locator:bPath+'#L1',content_hash:hash.sha256(bText),evidence_quote:bText}]}]};
 const C=fromRecorded('conflict','은빛-593 점검 충돌');
 fs.mkdirSync(path.join(root,'SYSTEM/CACHE/llmwiki'),{recursive:true});
 const jobs=load('llmwiki-batch-job-store'),jobStore=jobs.createBatchJobStore({storage:jobs.createNodeStorage(path.join(root,'SYSTEM/CACHE/llmwiki'))});await jobStore.load();
 const jobIds={};for(const item of [A,B,C]){const c=item.grounded_claims[0].citations[0];const j=await jobStore.createJob({request_key:hash.sha256(item.review_id),sources:[{source_id:c.source_id,revision_hash:c.content_hash}]});await jobStore.savePlanSnapshot({job_id:j.job_id,source_id:c.source_id,source_revision:c.content_hash,inventory_hash:hash.sha256(JSON.stringify(item.grounded_claims)),plan_hash:hash.sha256(item.document_body),plan_revision:1,status:'compiled',plan:{plan_version:'fixture_document_v1',pages:[]}});jobIds[item.review_id]=j.job_id;}
 class RealModal extends Modal {constructor(){super(realApp);}}
 function openText(p){const file=files.get(String(p).split('#')[0]);if(!file)throw Error('fixture_source_missing');const modal=new RealModal();modal.onOpen=()=>{modal.contentEl.createEl('h2',{text:file.path});modal.contentEl.createEl('p',{text:'격리된 실제 Markdown · '+hash.sha256(read(file))});modal.contentEl.createEl('pre',{text:read(file)});};modal.open();events.push({kind:'open',path:file.path});}
 let wikiUI;const session={};function openReview(item){return review.open({app:isolated,Modal:RealModal,item,jobStore,jobId:jobIds[item.review_id],onOpenSource:openText,onComplete:r=>{completions.push({item:item.title,result:r});save();},onStateChange:save});}
 async function save(){const result=await reader.create().read({app:isolated});fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({scope:'actual Obsidian Modal/controller with isolated filesystem adapter; recorded A/C analysis, not whole ingest entry',vault_root:root,completions,events,provider,reader:result.rows?.map(r=>({path:r.path,revision:r.canonical_revision,trust:r.trust_status})),conversation:wikiUI?.getConversation(),operational_writes:0},null,2));for(const row of result.rows||[])fs.writeFileSync(path.join(out,path.basename(row.path)),read(files.get(row.path)));}
 const modal=new RealModal();modal.onOpen=()=>{const e=modal.contentEl;e.createEl('h2',{text:'LLM Wiki · 격리 UI 검증'});e.createEl('p',{text:'운영 자료와 분리된 시험입니다. A/C 분석은 이전 실제 응답 재사용, 적용은 기존 검토 UI에서 명시적으로 수행합니다.'});for(const [label,item] of [['A 새 문서 검토',A],['B 기존 문서 보완 검토',B],['C 상충 변경안 검토',C]]){const b=e.createEl('button',{text:label});b.onclick=()=>openReview(item);}
 const open=e.createEl('button',{text:'작성된 해솔 문서 열기'});open.onclick=()=>openText('ZETA/PERMANENT/해솔-842 점검.md');
 const capture=e.createEl('button',{text:'시험 결과 기록'});capture.onclick=save;
 const panel=e.createDiv();wikiUI=surface.mountLlmWikiWikiSurface({app:isolated,container:panel,obsidian:{Modal:RealModal},readService,readAdapter,conversationSession:session,getSelectedSource:()=>({path:expectations.cases[0].virtual_path,content_hash:expectations.cases[0].sha256}),onOpenCitation:c=>openText(c.source_path),onOpenBeside:openText,confirmConsent:async()=>false});};modal.onClose=()=>{wikiUI?.destroy();save();};modal.open();globalThis.__llmWikiIsolatedUi={modal,isolated,save,root,openReview,items:{A,B,C}};
 fs.writeFileSync(path.join(out,'expected.json'),JSON.stringify({defined_before_ui:true,A:'6 conditions + memo; actual approved write + reader',B:'same target; identifier added; source A/B',C:'10/20 conflict + unknown priority; no canonical write',repeat:'no_change zero extra writes',conversation:'built Wiki identifier answer + grounded followup',whole_ingest:'NOT RUN: analysis replay',provider:'existing Runtime only; no new grant'},null,2));return {ready:true,root};
};
