'use strict';
// Isolated physical Markdown Vault. Synthetic/reused non-sensitive provider evidence only.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{performance}=require('node:perf_hooks');
const ROOT=path.resolve(__dirname,'../../..'),V=path.join(ROOT,'SYSTEM/Views');
const review=require(path.join(V,'llmwiki-document-canonical-review.js')),store=require(path.join(V,'knowledge-candidate-store.js')),hash=require(path.join(V,'llmwiki-hash.js')),read=require(path.join(V,'llmwiki-resurfacing-read-adapter.js')),wiki=require(path.join(V,'llmwiki-wiki-read-adapter.js')),obsidian=require(path.join(V,'llmwiki-obsidian-adapter.js'));
const expectations=JSON.parse(fs.readFileSync(path.join(ROOT,'artifacts/llmwiki-productization-20260909/expectations.json'),'utf8'));
const recorded=JSON.parse(fs.readFileSync(path.join(ROOT,'artifacts/llmwiki-productization-20260909/live-inspection.json'),'utf8'));
const vaultRoot=fs.mkdtempSync(path.join(__dirname,'vault-')),files=new Map(),events=[];
const real=p=>{const x=path.resolve(vaultRoot,p);assert.ok(x.startsWith(vaultRoot+path.sep));return x;};
const readBytes=f=>fs.readFileSync(real(f.path),'utf8');
const app={vault:{ getAbstractFileByPath:p=>files.get(p)||null,getFiles:()=>[...files.values()],getMarkdownFiles:()=>[...files.values()].filter(f=>f.extension==='md'),read:async f=>readBytes(f),cachedRead:async f=>readBytes(f),createFolder:async p=>fs.mkdirSync(real(p),{recursive:true}),create:async(p,b)=>{fs.mkdirSync(path.dirname(real(p)),{recursive:true});fs.writeFileSync(real(p),b,{flag:'wx'});const f={path:p,extension:p.endsWith('.md')?'md':'json',basename:path.basename(p,'.md')};files.set(p,f);events.push({action:'create',path:p});return f;},modify:async(f,b)=>{fs.writeFileSync(real(f.path),b);events.push({action:'modify',path:f.path});},delete:async f=>{fs.unlinkSync(real(f.path));files.delete(f.path);events.push({action:'delete',path:f.path});}},metadataCache:{getFileCache:f=>{try{return{frontmatter:store.parseLifecycleDocument(readBytes(f))};}catch(_){return{frontmatter:{}};}}}};
const fields={knowledge_kind:'claim',knowledge_domain:'coding',knowledge_topics:'ai',application_trigger:'실내 합성 모형 점검',application_contexts:'coding/ai',conditions:'실내 모형에만 적용',exclusions:'실외 적용 금지. 경고등 점등 시 즉시 중단하고 재개 금지.',invalidation_conditions:'원문 또는 적용 조건 변경',relation_status:'resolved',classification:'epistemic',evidence_strength:'sufficient'};
const artifact=(name,value)=>fs.writeFileSync(path.join(__dirname,name),typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');
const expectation={recorded_at:new Date().toISOString(),before_execution:true,A:'기록된 실제 provider의 여섯 조건 모두 최종 Markdown 유지; reader trusted',B:'A의 같은 경로 보완; 기록식별자 추가; 사용자메모 유지; real Wiki link 유효',C:'기록된 은빛593 10분/20분/우선순위 미상 그대로 변경안에 보존; conflict gate로 canonical 승인불가',D:'B 동일 입력 재처리 no_change, provider0, 내용/출처/link 중복0',approval:'격리 시험 harness의 명시적 사용자승인 시뮬레이션; 실제사람 또는 실제ObsidianUI 검증 아님',provider:'A/C 이전 actual provider evidence 재사용; B/링크대상은 합성원문 직접추출; 이번 provider calls0'};artifact('expected.json',expectation);
function fromRecorded(id,title){const r=recorded.results.find(r=>r.id===id).result;return{review_id:`review_disk_${id}`,title,document_body:`# ${title}\n\n${r.answers.map(a=>`${a.text} [원문](${a.citation.source_path.split('/').map(encodeURIComponent).join('/')}#${a.citation.locator.split('#')[1]})`).join('\n\n')}\n${(r.review_notes||[]).map(x=>`\n> ${x}`).join('')}\n`,grounded_claims:r.answers.map(a=>({text:a.text,citations:[{...a.citation,evidence_quote:a.citation.excerpt}]}))};}
async function direct(id,title,text){const p=`INBOX/${id}.md`;await app.vault.create(p,text);return{review_id:`review_disk_${id}`,title,document_body:`## ${title}\n${text}\n`,grounded_claims:[{text,citations:[{source_id:`source_${id}`,source_path:p,locator:`${p}#L1`,content_hash:hash.sha256(text),evidence_quote:text}]}]};}
const flow=review.create({app});
async function applyItem(item,extra={}){const start=performance.now(),p=await flow.prepare({item,fields,...extra});assert.equal(p.ok,true,JSON.stringify(p));const prepared=performance.now();assert.equal(p.status,'review',JSON.stringify(p));const result=await flow.apply(p.value,{approved:true,claims_accepted:true,packet_hash:p.value.packet_hash});assert.equal(result.ok,true,JSON.stringify(result));return{result,preview:p.value,timings:{prepare:prepared-start,apply_and_reader:performance.now()-prepared,total:performance.now()-start}};}
(async()=>{
 for(const c of expectations.cases)await app.vault.create(c.virtual_path,c.text);
 const A=fromRecorded('conditions','해솔-842 점검');A.document_body+='\n## 사용자 메모\n시험용 모형에만 적용한다는 개인 검토 메모를 보존한다.\n';const a=await applyItem(A);artifact('A-created.md',a.preview.after);
 const linked=await direct('indicator_reference','모형 식별 기록','장치 식별자는 서로 다른 모형의 기록을 구분하는 데 사용한다.');const reference=await applyItem(linked);
 const B=await direct('supplement_b','점검 기록 보완','해솔-842 점검 기록에는 장치 식별자를 함께 적는다.');B.related_knowledge=[{path:reference.result.target_path,title:'모형 식별 기록'}];
 const before=readBytes(files.get(a.result.target_path));artifact('B-before.md',before);
 const b=await applyItem(B,{target_path:a.result.target_path});artifact('B-after.md',b.preview.after);
 assert.equal(b.result.target_path,a.result.target_path);for(const claim of A.grounded_claims)assert.ok(b.preview.after.includes(claim.text));assert.ok(b.preview.after.includes(B.grounded_claims[0].text));assert.ok(b.preview.after.includes('개인 검토 메모를 보존한다.'));
 const link=`[[${reference.result.target_path.replace(/\.md$/u,'')}]]`;assert.ok(b.preview.after.includes(link));assert.ok(fs.existsSync(real(reference.result.target_path)));
 const C=fromRecorded('conflict','은빛-593 점검 충돌');artifact('C-conflict-proposal.md',C.document_body);
 assert.ok(C.document_body.includes('10분'));assert.ok(C.document_body.includes('20분'));assert.ok(C.document_body.includes('우선순위'));
 const beforeC=events.length;const c=await flow.prepare({item:C,fields:{...fields,relation_status:'conflict'}});assert.equal(c.ok,false);assert.equal(c.reason,'promotion_review_required');assert.equal(events.length,beforeC);artifact('C-conflict-result.json',c);
 const writesBeforeRepeat=events.length,repeatStart=performance.now();const repeat=await flow.prepare({item:B,fields,target_path:b.result.target_path});const repeatMs=performance.now()-repeatStart;assert.equal(repeat.status,'no_change',JSON.stringify(repeat));assert.equal(events.length,writesBeforeRepeat);
 const rows=await read.create().read({app});assert.equal(rows.ok,true);assert.equal(rows.rows.length,2);const snapshot=wiki.buildSnapshot({collection_revision:hash.sha256(rows.rows.map(r=>r.canonical_revision).join('')),assets:rows.rows});assert.equal(snapshot.counts.verified,2);
 const reused=rows.rows.find(r=>r.path===a.result.target_path);assert.ok(reused.canonical_bytes.includes(B.grounded_claims[0].text));
 const lookup=require(path.join(V,'llmwiki-canonical-overlap.js')).classify({page_title:A.title,claims:B.grounded_claims,canonical_documents:rows.rows.map(r=>({candidate_id:r.canonical_id,title:r.title,content:r.canonical_bytes,read_only:true}))});assert.equal(lookup.ok,true);assert.ok(lookup.candidates.some(c=>c.candidate_id===reused.canonical_id));
 const adapter=obsidian.createObsidianAdapter(app);const authorities=await adapter.readFinalizedCanonicalAuthorities();const binding=authorities.map(obsidian.finalizedCanonicalAuthorityData).find(x=>x.path===a.result.target_path);const document=store.parseLifecycleDocument(readBytes(files.get(a.result.target_path)));
 assert.equal(binding.canonical_v2_authority.claim_set_hash,document.claim_set_hash);assert.equal(binding.revision,hash.sha256(readBytes(files.get(a.result.target_path))));assert.equal(binding.canonical_v2_authority.sources.length,2);
 const result={status:'PASS',vault_root:vaultRoot,scope:'isolated physical filesystem Vault using current production review/writer/reader; no real Obsidian UI',provider_calls_this_run:0,provider_evidence:'A/C reused live-inspection.json actual provider recordings',A:{...a.result,timings:a.timings,conditions_preserved:6},B:{...b.result,timings:b.timings,source_count:2,canonical_document_count:2,note:'2 means main updated Knowledge + independently approved link target; no duplicate main Knowledge'},C:{status:'held',reason:c.reason,writes:0},D:{...repeat,latency_ms:repeatMs,additional_writes:0,provider_calls:0},link:{markdown:link,target_exists:true,count:b.preview.after.split(link).length-1},reader:{status:rows.status,verified:snapshot.counts.verified,updated_body_reusable:true,rows:rows.rows.map(r=>({path:r.path,trust_status:r.trust_status,revision:r.canonical_revision}))},next_source_existing_wiki_lookup:lookup,authority:{claim_set_hash_matches:true,revision_matches:true,source_ids:binding.canonical_v2_authority.sources.map(s=>s.source_id)},events,operational_writes:0,approval:'explicit test-harness simulation',real_ui:'NOT RUN'};
 artifact('result.json',result);process.stdout.write(JSON.stringify(result,null,2)+'\n');
})().catch(error=>{artifact('failure.json',{message:error.message,stack:error.stack,vault_root:vaultRoot});process.stderr.write(error.stack+'\n');process.exitCode=1;});
