"use strict";
const assert = require("node:assert/strict");
const projection = require("./auction-key-value-projection.js");
const snapshot = { groups: { "부산광역시|해운대구|우동|오피스텔": { key_value_won_per_pyeong: 10000000, q1_won_per_pyeong: 9000000, q3_won_per_pyeong: 11000000, case_count: 12, building_count: 5, confidence: "usable", period_start: "2025-09-01", period_end: "2026-08-31" } } };
const result = projection.project({ region_sido: "부산광역시", region_sigungu: "해운대구", region_dong: "우동", property_type: "오피스텔", exclusive_area: "33.05785㎡", expected_bid: 90000000 }, snapshot);
assert.equal(result.available, true);
assert.equal(result.legal_dong, "우동");
assert.equal(result.comparison.won_per_pyeong, 9000000);
assert.equal(result.comparison.ratio, 0.9);
assert.equal(result.comparison.position, "키값 근접");
assert.equal(projection.project({ region_sido: "부산광역시", region_sigungu: "해운대구", region_dong: "중동", property_type: "아파트" }, snapshot).available, false);
console.log("auction key value projection tests: PASS");
