"use strict";
const assert=require("node:assert/strict"),test=require("node:test"),hash=require("../../../../../Views/llmwiki-hash.js"),selector=require("../../../../../Views/llmwiki-user-source-selector.js");
test("lists eligible INBOX markdown without hashing every full document",async()=>{const files=[{path:"INBOX/서울투자반.md"},{path:"INBOX/Private/비밀.md"},{path:"INBOX/Processed/완료.md"},{path:"INBOX/민감.md"},{path:"KNOWLEDGE/정본.md"}],bytes=new Map([[files[0].path,"# 서울투자반\n내용"],[files[1].path,"# 비밀"],[files[2].path,"# 완료"],[files[3].path,"---\nprivate: true\n---\n# 민감"],[files[4].path,"# 정본"]]),vault={getMarkdownFiles:()=>files,cachedRead:file=>Promise.resolve(bytes.get(file.path))},privacy={classifyInboxSource:({source_path})=>({route:source_path.startsWith("INBOX/")?"knowledge":"ignored",outbound_allowed:true})};const rows=await selector.listInboxSources({vault,hash,privacy});assert.deepEqual(rows.map(x=>x.path),["INBOX/서울투자반.md"]);assert.equal(rows[0].title,"서울투자반");assert.equal(rows[0].source_kind,"inbox");assert.deepEqual(rows[0].provider_modes,["direct"]);assert.equal(Object.hasOwn(rows[0],"content_hash"),false)});
test("pins exactly one selected source revision",async()=>{const bytes="# 서울투자반\n내용",file={path:"INBOX/서울투자반.md"},vault={getAbstractFileByPath:path=>path===file.path?file:null,cachedRead:async()=>bytes},option={path:file.path,title:"서울투자반",source_kind:"inbox"};const pinned=await selector.pinSelection(option,vault,hash);assert.equal(pinned.ok,true);assert.equal(pinned.option.content_hash,hash.sha256(bytes));assert.equal(option.content_hash,undefined)});
test("blocks unsafe paths and private frontmatter",()=>{assert.equal(selector.eligibleInboxPath("INBOX/../SYSTEM/x.md","x"),false);assert.equal(selector.eligibleInboxPath("INBOX/Private/x.md","x"),false);assert.equal(selector.eligibleInboxPath("INBOX/x.md","---\nprivacy: private\n---\nx"),false);assert.equal(selector.eligibleInboxPath("INBOX/x.md","# x"),true)});
test("selection is invalidated when source bytes change",()=>{const bytes="# 자료\n원문",option={path:"INBOX/자료.md",source_kind:"inbox",content_hash:hash.sha256(bytes)};assert.equal(selector.verifySelection(option,bytes,hash).ok,true);assert.deepEqual(selector.verifySelection(option,`${bytes}!`,hash),{ok:false,reason:"selected_source_changed"})});
test("reads eligible INBOX candidates concurrently",async()=>{let active=0,maxActive=0;const files=Array.from({length:8},(_,index)=>({path:`INBOX/자료 ${index}.md`})),vault={getMarkdownFiles:()=>files,cachedRead:async(file)=>{active+=1;maxActive=Math.max(maxActive,active);await new Promise(resolve=>setImmediate(resolve));active-=1;return`# ${file.path}`}},privacy={classifyInboxSource:()=>({route:"knowledge",outbound_allowed:true})};const rows=await selector.listInboxSources({vault,hash,privacy});assert.equal(rows.length,8);assert.ok(maxActive>1,`expected concurrent reads, observed ${maxActive}`)});
test("listing hashes paths only and defers full bytes until selection",async()=>{const file={path:"INBOX/큰 자료.md"},bytes="# 큰 자료\n"+"본문".repeat(10000),hashed=[],spyHash={sha256(value){hashed.push(value);return"a".repeat(64)}},vault={getMarkdownFiles:()=>[file],getAbstractFileByPath:()=>file,cachedRead:async()=>bytes},privacy={classifyInboxSource:()=>({route:"knowledge",outbound_allowed:true})};const [option]=await selector.listInboxSources({vault,hash:spyHash,privacy});assert.deepEqual(hashed,[file.path]);const pinned=await selector.pinSelection(option,vault,spyHash);assert.equal(pinned.ok,true);assert.deepEqual(hashed,[file.path,bytes])});
test("metadata cache avoids full document reads while preserving privacy and title",async()=>{const visible={path:"INBOX/자료.md",basename:"자료"},hidden={path:"INBOX/민감.md",basename:"민감"};let reads=0;const vault={getMarkdownFiles:()=>[visible,hidden],cachedRead:async()=>{reads+=1;return"# unexpected"}},metadataCache={getFileCache:file=>file===visible?{frontmatter:{},headings:[{level:1,heading:"캐시 제목"}]}:{frontmatter:{private:true},headings:[]}},privacy={classifyInboxSource:({metadata})=>({route:metadata.private?"hold":"knowledge",outbound_allowed:metadata.private!==true})};const rows=await selector.listInboxSources({vault,metadataCache,hash,privacy});assert.deepEqual(rows.map(row=>row.title),["캐시 제목"]);assert.equal(reads,0)});
