"use strict";
const assert=require("node:assert/strict"),path=require("node:path"),test=require("node:test");
const ROOT=path.resolve(__dirname,"../../../../../..");const gate=require(path.join(ROOT,"SYSTEM/Views/llmwiki-golden-quality-gate.js"));
const source="권리산정기준일 이후 지분을 나누면 현금청산 위험이 있다. 대항력은 전입신고 다음 날 0시에 발생한다. 갭은 매매가와 전세가의 차이다.";
const good=`---\ntype: wiki-preview\nstatus: review\n---\n# 소액 정비사업 투자 점검\n\n> [!warning] 문서 성격\n> 실제 거래 전 최신 규정을 확인한다.\n\n## 한눈에 보기\n권리와 자금 위험을 먼저 확인한다.\n\n## 권리 확인\n권리산정기준일 이후 지분 분할은 현금청산 위험이 있다.\n\n## 계약과 자금\n대항력은 전입신고 다음 날 0시에 발생한다. 갭은 매매가와 전세가의 차이다.\n\n## 주요 위험\n규정 변경과 현금청산 가능성을 확인한다.\n\n## 실전 체크리스트\n- [ ] 권리산정기준일을 확인했다.\n\n## 원문\n- [[서울투자반]]\n`;
test("golden gate accepts a scoped readable Wiki with preserved critical facts",()=>{const r=gate.evaluate({source_text:source,document_text:good,source_path:"INBOX/서울투자반.md"});assert.equal(r.ok,true,r.issues?.join(","));assert.equal(r.status,"publishable_preview");assert.match(r.receipt.receipt_hash,/^[0-9a-f]{64}$/u);assert.equal(r.metrics.structure_score,1);assert.equal(r.metrics.critical_token_recall,1);assert.equal(r.metrics.style_score,1)});
test("golden gate rejects missing structure unsupported numbers and internal prose",()=>{const bad="# 초안\nclaim_abc와 공주가를 참고하면 대항력은 3일 뒤 발생한다. 무조건 투자해야 한다.";const r=gate.evaluate({source_text:source,document_text:bad,source_path:"INBOX/서울투자반.md"});assert.equal(r.ok,false);assert.equal(r.issues.includes("required_sections_missing"),true);assert.equal(r.issues.includes("unsupported_numeric_token"),true);assert.equal(r.issues.includes("internal_token_exposed"),true);assert.equal(r.issues.includes("source_jargon_exposed"),true);assert.equal(r.issues.includes("overassertive_prose"),true)});

test("numerics distinguishes Markdown ordered markers from attached numeric tokens",()=>{assert.deepEqual(gate.numerics("5. 원판"),[]);assert.deepEqual(gate.numerics("5.원"),["5.원"]);});
test("golden gate inherits title numbers, ignores ordered-list markers, and requires body-critical measurements",()=>{const sourceText="권리산정기준일 이후 지분을 나누면 현금청산 위험이 있다. 기준은 18mm이다.";const full=`---\ntype: wiki-preview\n---\n# 20260523\n\n> [!warning] 문서 성격\n> 실제 거래 전 최신 규정을 확인한다.\n\n## 한눈에 보기\n권리와 자금 위험을 먼저 확인한다.\n\n## 주요 위험\n18mm 깊이의 기준을 확인한다.\n\n## 실전 체크리스트\n5. 원판 상태를 확인한다.\n\n## 원문\n- [[서울투자반]]\n`;const input={source_text:sourceText,document_text:full,source_path:"INBOX/20260523.md"};const pass=gate.evaluate(input);assert.equal(pass.status,"publishable_preview");assert.equal(pass.metrics.unsupported_numeric_tokens.includes("20260523"),false);assert.equal(gate.numerics(full).includes("5"),false);const fail=gate.evaluate({...input,document_text:full.replace("18mm ","")});assert.equal(fail.status,"review_required");assert.equal(fail.issues.includes("critical_token_missing"),true)});
