"use strict";
const assert=require("node:assert/strict"),test=require("node:test"),hash=require("../../../../../Views/llmwiki-hash.js"),workbench=require("../../../../../Views/llmwiki-golden-preview-workbench.js");
const documentBytes="# 서울 점검 가이드\n\n## 원문\n[[서울투자반]]\n";
function receipt(overrides={}){return {ok:true,status:"publishable_preview",issues:[],metrics:{structure_score:1,critical_token_recall:1,style_score:1,unsupported_numeric_tokens:[],missing_critical_tokens:[]},receipt:{source_path:"INBOX/서울투자반.md",document_hash:hash.sha256(documentBytes),receipt_hash:"a".repeat(64)},...overrides}}
test("publishable preview exposes human review without canonical promotion",()=>{const row=workbench.inspectPreview({document_path:"SYSTEM/CACHE/llmwiki/서울 점검 가이드.md",document_bytes:documentBytes,receipt:receipt()});assert.equal(row.status,"publishable_preview");assert.equal(row.can_mark_reviewed,true);assert.equal(row.document_path,"SYSTEM/CACHE/llmwiki/서울 점검 가이드.md");assert.equal(row.source_path,"INBOX/서울투자반.md");assert.equal(Object.hasOwn(row,"target_path"),false);assert.equal(Object.hasOwn(row,"promotion_operation"),false)});
test("tampered preview is blocked at the review boundary",()=>{const row=workbench.inspectPreview({document_path:"SYSTEM/CACHE/llmwiki/서울 점검 가이드.md",document_bytes:`${documentBytes}변조`,receipt:receipt()});assert.equal(row.status,"review_required");assert.equal(row.can_mark_reviewed,false);assert.equal(row.issues.includes("document_hash_mismatch"),true)});
test("incomplete quality metrics cannot be marked reviewed",()=>{const row=workbench.inspectPreview({document_path:"SYSTEM/CACHE/llmwiki/서울 점검 가이드.md",document_bytes:documentBytes,receipt:receipt({status:"review_required",metrics:{structure_score:1,critical_token_recall:.5,style_score:1}})});assert.equal(row.can_mark_reviewed,false);assert.equal(row.issues.includes("gate_not_publishable"),true);assert.equal(row.issues.includes("quality_metrics_incomplete"),true)});
test("loader pairs receipt only with its exact preview markdown",async()=>{const receiptPath="SYSTEM/CACHE/llmwiki/서울 점검 가이드.receipt.json",documentPath="SYSTEM/CACHE/llmwiki/서울 점검 가이드.md",files=[{path:receiptPath},{path:documentPath}],bytes=new Map([[receiptPath,JSON.stringify(receipt())],[documentPath,documentBytes]]),vault={getFiles:()=>files,getAbstractFileByPath:path=>files.find(file=>file.path===path)||null,cachedRead:file=>Promise.resolve(bytes.get(file.path))};const rows=await workbench.loadPreviews(vault);assert.equal(rows.length,1);assert.equal(rows[0].can_mark_reviewed,true)});
test("tampered orchestration provenance blocks human review",()=>{const base=receipt(),body={orchestrator_version:"llmwiki_golden_wiki_orchestrator_v1",document_path:"SYSTEM/CACHE/llmwiki/서울 점검 가이드.md",source_path:"INBOX/서울투자반.md",source_revision:"b".repeat(64),scope:null,source_bytes:100,chunk_count:1,pack_count:1,scoped_claim_ids:["claim_1"],gate_receipt_hash:base.receipt.receipt_hash},stable=value=>value===null||typeof value!=="object"?JSON.stringify(value):Array.isArray(value)?`[${value.map(stable).join(",")}]`:`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`,valid={...base,...body,orchestration_receipt_hash:hash.sha256(stable(body))};assert.equal(workbench.inspectPreview({document_path:body.document_path,document_bytes:documentBytes,receipt:valid}).can_mark_reviewed,true);const tampered={...valid,source_revision:"c".repeat(64)};const row=workbench.inspectPreview({document_path:body.document_path,document_bytes:documentBytes,receipt:tampered});assert.equal(row.can_mark_reviewed,false);assert.equal(row.issues.includes("orchestration_receipt_invalid"),true)});
